from prometheus_client import Counter, Histogram

# Metric Definitions
GENERATED_TOKENS_TOTAL = Counter(
    "novalm_generated_tokens_total",
    "Total number of tokens generated by the model",
    ["model"]
)

INFERENCE_LATENCY_SECONDS = Histogram(
    "novalm_inference_latency_seconds",
    "Time taken for inference request processing",
    ["model"]
)
